version: "3.5"
x-default: &default
  logging:
    options:
      max-size: "5M"
      max-file: "5"
services:
  srv:
    image: juxuny/log-server:v0.0.6
    entrypoint: 
      - /app/logd
      - "-d=/app/log"
    restart: always
    volumes:
      - ./tmp:/app/log
    ports:
      - "40000:40000"
  cleaner:
    image: juxuny/log-server:v0.1.0
    entrypoint:
      - sh
      - cleaner-entrypoint.sh
    restart: always
    volumes:
      - ./compress.sh:/app/compress.sh
      - ./cleaner-entrypoint.sh:/app/cleaner-entrypoint.sh
      - ./tmp:/app/log
    
