// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log_server.proto

package log_server // import "github.com/juxuny/log-server"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddReq struct {
	App                  string   `protobuf:"bytes,1,opt,name=app" json:"app,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_server_cb31fb26274f43ad, []int{0}
}
func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (dst *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(dst, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *AddReq) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type AddResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *AddResp) Reset()         { *m = AddResp{} }
func (m *AddResp) String() string { return proto.CompactTextString(m) }
func (*AddResp) ProtoMessage()    {}
func (*AddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_server_cb31fb26274f43ad, []int{1}
}
func (m *AddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResp.Unmarshal(m, b)
}
func (m *AddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResp.Marshal(b, m, deterministic)
}
func (dst *AddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResp.Merge(dst, src)
}
func (m *AddResp) XXX_Size() int {
	return xxx_messageInfo_AddResp.Size(m)
}
func (m *AddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddResp proto.InternalMessageInfo

func (m *AddResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_server_cb31fb26274f43ad, []int{2}
}
func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (dst *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(dst, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

type PingResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_server_cb31fb26274f43ad, []int{3}
}
func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResp.Unmarshal(m, b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
}
func (dst *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(dst, src)
}
func (m *PingResp) XXX_Size() int {
	return xxx_messageInfo_PingResp.Size(m)
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

type InfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *InfoReq) Reset()         { *m = InfoReq{} }
func (m *InfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()    {}
func (*InfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_server_cb31fb26274f43ad, []int{4}
}
func (m *InfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoReq.Unmarshal(m, b)
}
func (m *InfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoReq.Marshal(b, m, deterministic)
}
func (dst *InfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReq.Merge(dst, src)
}
func (m *InfoReq) XXX_Size() int {
	return xxx_messageInfo_InfoReq.Size(m)
}
func (m *InfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReq proto.InternalMessageInfo

type InfoResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *InfoResp) Reset()         { *m = InfoResp{} }
func (m *InfoResp) String() string { return proto.CompactTextString(m) }
func (*InfoResp) ProtoMessage()    {}
func (*InfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_server_cb31fb26274f43ad, []int{5}
}
func (m *InfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResp.Unmarshal(m, b)
}
func (m *InfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResp.Marshal(b, m, deterministic)
}
func (dst *InfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResp.Merge(dst, src)
}
func (m *InfoResp) XXX_Size() int {
	return xxx_messageInfo_InfoResp.Size(m)
}
func (m *InfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddReq)(nil), "log_server.AddReq")
	proto.RegisterType((*AddResp)(nil), "log_server.AddResp")
	proto.RegisterType((*PingReq)(nil), "log_server.PingReq")
	proto.RegisterType((*PingResp)(nil), "log_server.PingResp")
	proto.RegisterType((*InfoReq)(nil), "log_server.InfoReq")
	proto.RegisterType((*InfoResp)(nil), "log_server.InfoResp")
}

func init() { proto.RegisterFile("log_server.proto", fileDescriptor_log_server_cb31fb26274f43ad) }

var fileDescriptor_log_server_cb31fb26274f43ad = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4e, 0x85, 0x30,
	0x14, 0x86, 0x2f, 0xde, 0x1b, 0x90, 0x33, 0x91, 0xa3, 0x03, 0x41, 0x63, 0x4c, 0x27, 0x17, 0x8b,
	0x91, 0x27, 0xc0, 0xcd, 0xc4, 0xc1, 0xe0, 0xe6, 0x62, 0xc0, 0xd6, 0x8a, 0x01, 0x5a, 0x28, 0x18,
	0x7d, 0x22, 0x5f, 0xd3, 0xb4, 0x85, 0x28, 0x61, 0xfb, 0xf3, 0xf5, 0xfc, 0xf9, 0xbf, 0x14, 0xa2,
	0x46, 0x8a, 0x17, 0xcd, 0x87, 0x4f, 0x3e, 0x50, 0x35, 0xc8, 0x51, 0x22, 0xfc, 0x11, 0x42, 0xc1,
	0xcf, 0x19, 0x2b, 0x78, 0x8f, 0x11, 0xec, 0x4b, 0xa5, 0x62, 0xef, 0xd2, 0xbb, 0x0a, 0x0b, 0x13,
	0x11, 0xe1, 0xc0, 0xca, 0xb1, 0x8c, 0x8f, 0x2c, 0xb2, 0x99, 0x9c, 0x41, 0x60, 0xef, 0xb5, 0x32,
	0x85, 0x56, 0x8b, 0xa5, 0xd0, 0x6a, 0x41, 0x42, 0x08, 0x1e, 0xeb, 0x4e, 0x14, 0xbc, 0x27, 0x00,
	0xc7, 0x2e, 0x6a, 0x65, 0xf0, 0x7d, 0xf7, 0x26, 0x67, 0xec, 0xa2, 0x56, 0xb7, 0x3f, 0x1e, 0x84,
	0x0f, 0x52, 0x3c, 0x59, 0x11, 0xbc, 0x81, 0x7d, 0xce, 0x18, 0x22, 0xfd, 0xa7, 0xeb, 0xcc, 0x92,
	0x93, 0x0d, 0xd3, 0x8a, 0xec, 0x30, 0x83, 0x83, 0x99, 0xc0, 0xd5, 0xf3, 0xbc, 0x9f, 0x9c, 0x6e,
	0xe1, 0x52, 0x32, 0x02, 0xeb, 0xd2, 0x6c, 0xb7, 0x2e, 0x2d, 0x9e, 0x64, 0x77, 0x77, 0xf1, 0x7c,
	0x2e, 0xea, 0xf1, 0x7d, 0xaa, 0xe8, 0xab, 0x6c, 0xd3, 0x8f, 0xe9, 0x6b, 0xea, 0xbe, 0xd3, 0x46,
	0x8a, 0x6b, 0x77, 0x5a, 0xf9, 0xf6, 0x5f, 0xb3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xfd,
	0xf5, 0xe2, 0x6b, 0x01, 0x00, 0x00,
}
